[workspace]
members = [
    "task-01_1",
    "task-01_2",
    "task-02_1",
    "task-02_2",
    "task-03_1",
    "task-03_2",
    "task-04_1",
    "task-04_2",
    "task-05_1",
    "task-05_2",
    "task-06_1",
    "task-06_2",
    "task-07_1",
    "task-07_2",
]